import io
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from app.db.store import db_store

class PDFService:
    @staticmethod
    def generate_pdf_report(audit_id: str) -> bytes:
        audit = db_store.get_audit(audit_id)
        if not audit:
            company_name = "Sample Brand"
            domain = "samplebrand.com"
            conversion_score = 72
            trust_score = 68
            ux_score = 80
            annual_lift = 124500.0
            friction_points = []
            recommendations = ["Implement sticky mobile CTA", "Add review badge near buy button"]
        else:
            company_name = audit["company_name"]
            domain = audit["domain"]
            conversion_score = audit["conversion_score"]
            trust_score = audit["trust_score"]
            ux_score = audit["ux_score"]
            annual_lift = audit["revenue_opportunity"]["annual_revenue_lift"]
            friction_points = audit.get("friction_points", [])
            recommendations = audit.get("recommendations", [])

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()
        
        # Custom Styles
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            leading=28,
            textColor=colors.HexColor('#0F172A')
        )
        
        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=11,
            leading=14,
            textColor=colors.HexColor('#64748B')
        )

        heading2_style = ParagraphStyle(
            'ReportHeading2',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#1E293B'),
            spaceBefore=12,
            spaceAfter=6
        )

        body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor('#334155')
        )

        elements = []

        # Header Block
        elements.append(Paragraph("GROWTHPILOT AI — EXECUTIVE GROWTH AUDIT REPORT", subtitle_style))
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(f"Audit & Revenue Roadmap: <b>{domain}</b>", title_style))
        elements.append(Spacer(1, 2))
        elements.append(Paragraph(f"Target Account: {company_name} | Generated by GrowthPilot AI Agency Engine", subtitle_style))
        elements.append(Spacer(1, 10))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#E2E8F0'), spaceAfter=12))

        # Executive Metrics Table
        metrics_data = [
            ["Metric Category", "Score / Value", "Industry Benchmark", "Status"],
            ["Conversion Score", f"{conversion_score} / 100", "78 / 100", "Needs Optimization" if conversion_score < 75 else "Strong"],
            ["Trust & Credibility", f"{trust_score} / 100", "82 / 100", "Optimization Target"],
            ["UX & Layout Quality", f"{ux_score} / 100", "80 / 100", "Good"],
            ["Est. Annual Revenue Lift", f"${annual_lift:,.0f}", "+15% ARR", "High Opportunity"]
        ]

        t_metrics = Table(metrics_data, colWidths=[150, 110, 140, 140])
        t_metrics.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
            ('TOPPADDING', (0, 0), (-1, 0), 6),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8FAFC')),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#1E293B')),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
        ]))

        elements.append(t_metrics)
        elements.append(Spacer(1, 14))

        # Section 1: Executive Summary
        elements.append(Paragraph("1. Executive Summary & Revenue Opportunity", heading2_style))
        exec_summary_text = (
            f"Based on an automated end-to-end audit of <b>{domain}</b>, GrowthPilot AI identified 4 primary CRO friction points "
            f"currently suppressing your conversion rate. By fixing mobile CTA positioning, mini-cart threshold indicators, "
            f"and social proof placement, {company_name} can capture an estimated <b>${annual_lift:,.0f}</b> in additional annual revenue."
        )
        elements.append(Paragraph(exec_summary_text, body_style))
        elements.append(Spacer(1, 10))

        # Section 2: Friction Points
        elements.append(Paragraph("2. Critical Friction Points Diagnosed", heading2_style))
        if friction_points:
            for idx, fp in enumerate(friction_points, 1):
                fp_title = f"<b>Friction #{idx}: {fp['title']}</b> ({fp['category']} - Severity: {fp['severity'].upper()})"
                fp_desc = f"<i>Location:</i> {fp['location']}<br/><i>Impact:</i> {fp['impact']}<br/><i>Fix:</i> {fp['recommended_fix']}"
                elements.append(Paragraph(fp_title, body_style))
                elements.append(Paragraph(fp_desc, body_style))
                elements.append(Spacer(1, 6))
        else:
            elements.append(Paragraph("• Primary CTA hidden below fold on mobile viewports (<390px).", body_style))
            elements.append(Paragraph("• Social proof review badges separated from order buy button by 2 full page scrolls.", body_style))
            elements.append(Paragraph("• Mini-cart drawer missing dynamic free shipping progress bar.", body_style))

        elements.append(Spacer(1, 10))

        # Section 3: Recommendations
        elements.append(Paragraph("3. Recommended Growth Sprint Action Plan", heading2_style))
        if recommendations:
            for rec in recommendations:
                elements.append(Paragraph(f"• {rec}", body_style))
                elements.append(Spacer(1, 3))
        else:
            elements.append(Paragraph("• Deploy fixed mobile sticky buy bar.", body_style))
            elements.append(Paragraph("• Integrate review badge directly above primary CTA button.", body_style))

        elements.append(Spacer(1, 20))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CBD5E1'), spaceAfter=10))
        elements.append(Paragraph("GrowthPilot AI Engine — Confidential Growth Report & Sales Brief", subtitle_style))

        doc.build(elements)
        buffer.seek(0)
        return buffer.getvalue()
